### ISSUE TITLE
couldn't resolve module/action 'opkg'

### ISSUE THREAD

**Issue by m8522s** [imp1sh/ansible_openwrt#1]
I'm trying to install an OpenWrt package using your Ansible role. However, even with the collection installed, I run into this output:

```
TASK [imp1sh.ansible_openwrt.ansible_openwrtpackages : Install tasks] *****************************************
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'opkg'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/imp1sh/ansible_openwrt/roles/ansible_openwrtpackages/tasks/install.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  when: openwrt_packagesinstallmergedgroup is defined\n- name: Install packages\n  ^ here\n"}
```

The mentioned file `/root/.ansible/collections/ansible_collections/imp1sh/ansible_openwrt/roles/ansible_openwrtpackages/tasks/install.yml` is present.
This is the first time I use your collection, so this is most likely not a but and I am doing something wrong. Can you point me in the right direction?

I reduced the playbook to a minimal (non-)working example:
```
- hosts: localhost
  connection: local
  become: no
  roles:
  - imp1sh.ansible_openwrt.ansible_openwrtpackages
 ```

The host_vars file for localhost is:
```
openwrt_packagesinstallhost:
  - "vnstat2"
```

ansible [core 2.12.1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.9 (main, Jan 16 2022, 15:28:46) [GCC 8.4.0]
  jinja version = 3.0.3
  libyaml = True

/etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.1'
DISTRIB_REVISION='r16325-88151b8303'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 21.02.1 r16325-88151b8303'
DISTRIB_TAINTS=''

**Comment by imp1sh** [comment]
It looks like you're trying to run the playbook on the host you have Ansible installed on. It one doesn't know opkg as it's an OpenWrt specific command. You should not try to run it on localhost but on the OpenWrt system.
Make sure:
* The OpenWrt system is reachable from your ansible host
* python3 installed on the OpenWrt host
* take ssh key from your user on the Ansible host and install it onto the OpenWrt device via its WebGUI System - Administration - SSH Keys
* Update your ansible config so it doesn't use localhost but the hostname or IP of the OpenWrt device

**Comment by m8522s** [comment]
Thanks for your quick reply.
Yes, I run Ansible on the OpenWrt host and skip the "ssh to localhost" section with the option `connection: local`. I'm working on a solution where OpenWrt hosts fetch their playbooks from a central webserver and apply them locally.
Is that possible with your collection (or with Ansible in general)?

**Comment by imp1sh** [comment]
Can we switch channels? Maybe we can talk via Matrix or Jabber/XMPP?

**Comment by m8522s** [comment]
Sure. Let me try to reach you by email...
