### ISSUE TITLE
Ansible galaxy comand line

### ISSUE THREAD

**Issue by AHallmann** [imp1sh/ansible_openwrt#2]
galaxy didn't load your collection with the statements you documented. (Downloaded file wasn't a tar ball.) 

The following statement resolved my problem:
Whit a ansible-galaxy collection install git+https://github.com/imp1sh/ansible_nftwallcollection.git

Andreas

P.S.: Thanks for sharing your work. ;-)

**Comment by imp1sh** [comment]
Thank you very much for the feedback, I will update the documentation right away.
