### ISSUE TITLE
Ansible Galaxy has old release (0.1.5). Should update to (0.1.6)

### ISSUE THREAD

**Issue by PhilipWhiteside** [imp1sh/ansible_openwrt#4]
The Ansible Galaxy has old release (0.1.5). There are fixes in 0.1.6 that I needed as a new user of this collection. 

Thank you for creating this, it's been great to use.

**Comment by imp1sh** [comment]
Thank you for your feedback. I will update soon.

**Comment by imp1sh** [comment]
I just released Version 0.2.0.

**Comment by PhilipWhiteside** [comment]
That's great, it's working brilliantly for me. I can see v2 in Galaxy, though the GitHub release is still behind. I have more options I'd like to add but don't want to PR onto an older version.
