### ISSUE TITLE
Support for BATMAN mesh setup

### ISSUE THREAD

**Issue by skywalker123p** [imp1sh/ansible_openwrt#7]
Please add support for BATMAN mesh setup. thanks

**Comment by imp1sh** [comment]
I will take a look into it. I guess you're referring to batman-adv.
https://openwrt.org/docs/guide-user/network/wifi/mesh/batman
Do you know if every aspect of batman-adv can be managed through UCI?

**Comment by imp1sh** [comment]
I'm sorry man I kind of forgot about that. I'll look into it in the next weeks.

**Comment by imp1sh** [comment]
Well I took a look at it and I'm sorry to tell that I won't be able to implement this. It's too time consuming since there are plenty of different things to consider. Feel free to send a PR.
